### ISSUE TITLE
question to q4osteam - detecting when update manager icon is in systray

### ISSUE THREAD

**Issue by seb3773** [seb3773/actioncenter-kicker-applet#3]
What I want is to detect the presence of the update manager icon in systray (not the fact that updates are availables, but only when update-manager is notifying there are updates availables) from a bash script. Is it possible ?

**Comment by q4osteam** [comment]
As far as we know, there is no way available. We could add such an feature on our todo list, if you wish.

**Comment by seb3773** [comment]
For now, I'm doing it with xdotool, it works, but maybe it's not the "right/best" way to do it. What do you think ?

**Comment by q4osteam** [comment]
Yes, it's not an ideal solution, however it should work well. Unfortunately, it's not possible to check that more clean way, for ex. with dcop tool.

**Comment by seb3773** [comment]
OK. I think I will keep it that way for now, it works well, so no problem after all :)
