### ISSUE TITLE
Question - cmake build, what are the prerequisities and how to build

### ISSUE THREAD

**Issue by q4osteam** [seb3773/actioncenter-kicker-applet#8]
We have noticed you have added Cmake build support. That's great, however we are not able to compile yet. Cmake reports:
```
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at CMakeLists.txt:11 (include):
  include could not find requested file:
    TDEMacros
CMake Error at CMakeLists.txt:12 (tde_set_project_version):
  Unknown CMake command "tde_set_project_version".
-- Configuring incomplete, errors occurred!

```
So, what packages do we need to install and how to proceed in order to build and test the project ? We would suggest to post these instructions at the project description page too.

**Comment by seb3773** [comment]
I'm getting help from another github user, blu256, for the graphical aspects as it's not "optimal" yet. It's him who added cmake support. We need the TDE macros package to compile it now, it's the 'tde-cmake' package. 
But now, there's an annoying graphical bug (described here: https://github.com/seb3773/actioncenter-kicker-applet/issues/7 ) so please wait before it's corrected, it's 'not functionnal' in the actual state.

**Comment by q4osteam** [comment]
Thanks for the info, closing the issue.
